---
# image repo and tag
kube_ovn_container_image_repo: "{{ docker_image_repo }}/kubeovn/kube-ovn"
kube_ovn_container_image_tag: "{{ kube_ovn_version }}"
kube_ovn_vpc_container_image_repo: "{{ docker_image_repo }}/kubeovn/vpc-nat-gateway"
kube_ovn_vpc_container_image_tag: "{{ kube_ovn_version }}"
kube_ovn_dpdk_container_image_repo: "{{ docker_image_repo }}/kubeovn/kube-ovn-dpdk"
kube_ovn_dpdk_container_image_tag: "{{ kube_ovn_dpdk_version }}"

# request and limit
kube_ovn_db_cpu_request: 500m
kube_ovn_db_memory_request: 200Mi
kube_ovn_db_cpu_limit: 3000m
kube_ovn_db_memory_limit: 3000Mi
kube_ovn_node_cpu_request: 200m
kube_ovn_node_memory_request: 200Mi
kube_ovn_node_cpu_limit: 1000m
kube_ovn_node_memory_limit: 800Mi
kube_ovn_cni_server_cpu_request: 200m
kube_ovn_cni_server_memory_request: 200Mi
kube_ovn_cni_server_cpu_limit: 1000m
kube_ovn_cni_server_memory_limit: 1Gi
kube_ovn_controller_cpu_request: 200m
kube_ovn_controller_memory_request: 200Mi
kube_ovn_controller_cpu_limit: 1000m
kube_ovn_controller_memory_limit: 1Gi
kube_ovn_pinger_cpu_request: 100m
kube_ovn_pinger_memory_request: 200Mi
kube_ovn_pinger_cpu_limit: 200m
kube_ovn_pinger_memory_limit: 400Mi
kube_ovn_monitor_memory_request: 200Mi
kube_ovn_monitor_cpu_request: 200m
kube_ovn_monitor_memory_limit: 200Mi
kube_ovn_monitor_cpu_limit: 200m
kube_ovn_dpdk_node_cpu_request: 1000m
kube_ovn_dpdk_node_memory_request: 2Gi
kube_ovn_dpdk_node_cpu_limit: 1000m
kube_ovn_dpdk_node_memory_limit: 2Gi

kube_ovn_central_hosts: "{{ groups['kube_control_plane'] }}"
kube_ovn_central_replics: "{{ kube_ovn_central_hosts | length }}"
kube_ovn_controller_replics: "{{ kube_ovn_central_hosts | length }}"
kube_ovn_central_ips: |-
  {% for item in kube_ovn_central_hosts -%}
    {{ hostvars[item]['ip'] | default(hostvars[item]['fallback_ip']) }}{% if not loop.last %},{% endif %}
  {%- endfor %}

kube_ovn_ic_enable: false
kube_ovn_ic_auto_route: true
kube_ovn_ic_db_host: "127.0.0.1"
kube_ovn_ic_zone: "kubernetes"

# kube-ovn default subnet
kube_ovn_default_subnet: "ovn-default"
kube_ovn_default_vpc: "ovn-cluster"
kube_ovn_node_subnet: "join"
kube_ovn_mirror_iface: "mirror0"

# geneve or vlan
kube_ovn_network_type: geneve

# geneve, vxlan or stt. ATTENTION: some networkpolicy cannot take effect when using vxlan and stt need custom compile ovs kernel module
kube_ovn_tunnel_type: geneve

## The nic to support container network can be a nic name or a group of regex separated by comma e.g: 'enp6s0f0,eth.*', if empty will use the nic that the default route use.
# kube_ovn_iface: eth1
## The MTU used by pod iface in overlay networks (default iface MTU - 100)
# kube_ovn_mtu: 1333

## Enable hw-offload, disable traffic mirror and set the iface to the physical port. Make sure that there is an IP address bind to the physical port.
kube_ovn_hw_offload: false
# traffic mirror
kube_ovn_traffic_mirror: false

# kube_ovn_pool_cidr_ipv6: fd85:ee78:d8a6:8607::1:0000/112

# kube_ovn_default_provider_name: provider
# kube_ovn_default_vlan_interface_name: eth0

kube_ovn_external_address: 8.8.8.8
kube_ovn_external_address_ipv6: 2400:3200::1
kube_ovn_external_dns: alauda.cn

# kube_ovn_default_gateway: 10.233.64.1,fd85:ee78:d8a6:8607::1:0
kube_ovn_default_gateway_check: true
kube_ovn_default_logical_gateway: false

# u2o_interconnection
kube_ovn_u2o_interconnection: false

# kube_ovn_default_exclude_ips: 10.16.0.1
kube_ovn_node_switch_cidr: 100.64.0.0/16
kube_ovn_node_switch_cidr_ipv6: fd00:100:64::/64

## vlan config, set default interface name and vlan id
# kube_ovn_default_interface_name: eth0
kube_ovn_default_vlan_name: vlan100
kube_ovn_default_vlan_id: 100
kube_ovn_vlan_name: product

## pod nic type, support: veth-pair or internal-port
kube_ovn_pod_nic_type: veth_pair

## Enable load balancer
kube_ovn_enable_lb: true

## Enable network policy support
kube_ovn_enable_np: true

## Enable external vpc support
kube_ovn_enable_external_vpc: true

## Enable checksum
kube_ovn_encap_checksum: true

## enable ssl
kube_ovn_enable_ssl: false

## dpdk
kube_ovn_dpdk_enabled: false
kube_ovn_dpdk_tunnel_iface: br-phy

## bind local ip
kube_ovn_bind_local_ip_enabled: true

## enable compact
kube_ovn_enable_compact: false

## ovn northd n threads
kube_ovn_northd_n_threads: 1

## ovn leader probe interval
kube_ovn_leader_probe_interval: 5

## ovn probe interval
kube_ovn_probe_interval: 180000

# ovn northd probe interval
kube_ovn_northd_probe_interval: 5000

# ovn remote probe interval
kube_ovn_remote_probe_interval: 10000

# ovn remote openflow interval
kube_ovn_remote_openflow_interval: 180

## eip snat need configmap "ovn-vpc-nat-config" set by user first
kube_ovn_eip_snat_enabled: false

# ls dnat mod dl dst
kube_ovn_ls_dnat_mod_dl_dst: true

# ls ct skip dst lport ips
kube_ovn_ls_ct_skip_dst_lport_ips: true

# enable ecmp
kube_ovn_enable_ecmp: false

# enable metrics
kube_ovn_enable_metrics: true

# enable tproxy
kube_ovn_enable_tproxy: false

# ovs vsctl concurrency
kube_ovn_ovs_vsctl_concurrency: 100

# enable sercure service
kube_ovn_enable_secure_serving: false

# ovn exchange link name with ovs bridge name
kube_ovn_exchange_link_name: false

## keep vm ip
kube_ovn_keep_vm_ip: true

## cni config priority, default: 01
kube_ovn_cni_config_priority: "01"

# nodelocaldns_ip
nodelocaldns_ip: 169.254.25.10

# ovs db connection timeout
kube_ovn_ovsdb_connection_timeout: 3

# ovs db inactivity probe timeout
kube_ovn_ovsdb_inactivity_probe: 10

# kube ovn gc interval
kube_ovn_gc_interval: 360

# kube ovn inspect interval
kube_ovn_inspect_interval: 20
