---
kube_slice_cgroup: "/{{ kube_slice.split('-') | join('.slice/') }}/"
system_slice_cgroup: "/{{ system_slice.split('-') | join('.slice/') }}/"
enforce_node_allocatable_stub:
  pods: "{{ enforce_allocatable_pods }}"
  kube-reserved: "{{ enforce_allocatable_kube_reserved }}"
  system-reserved: "{{ enforce_allocatable_system_reserved }}"
enforce_node_allocatable: "{{ enforce_node_allocatable_stub | dict2items | selectattr('value') | map(attribute='key') }}"
